# Generated by Django 3.2.15 on 2022-08-09 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('car_year', models.IntegerField()),
                ('car_color', models.CharField(max_length=50)),
                ('car_price', models.IntegerField()),
                ('car_image', models.ImageField(null=True, upload_to='images/')),
                ('car_description', models.TextField()),
                ('car_status', models.BooleanField(default=True)),
                ('car_created_at', models.DateTimeField(auto_now_add=True)),
                ('car_is_deleted', models.BooleanField(default=False)),
                ('car_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_total', models.IntegerField()),
                ('order_created_at', models.DateTimeField(auto_now_add=True)),
                ('order_is_deleted', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=9)),
                ('order_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_color', models.CharField(max_length=50)),
                ('cart_quantity', models.IntegerField()),
                ('cart_is_deleted', models.BooleanField(default=False)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.cars')),
                ('cart_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
