# Generated by Django 3.2.15 on 2022-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_description',
            field=models.TextField(max_length=100),
        ),
    ]
