# Generated by Django 3.2.15 on 2022-08-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_account_dob'),
        ('Cars', '0002_alter_cars_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.account'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
